<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.45">
   <annotation>
      <documentation>1011: Innretning som planter kan klatre/støtte seg på.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="EierPlanteoppstøtting (test)Type">
      <annotation>
         <documentation>13315: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13315</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EierPlanteoppstøtting (test)EnumerationType nvdb:EierPlanteoppstøtting (test)OtherType"/>
   </simpleType>
   <simpleType name="EierPlanteoppstøtting (test)EnumerationType">
      <annotation>
         <documentation>13315: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13315</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23251</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23252</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23253</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23250</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23249</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <documentation>23254: Verdi benyttes inntil det er avklart hvem som er eier (ingen verdi tolkes som at vegeier er eier).</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23254</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EierPlanteoppstøtting (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="FestetPåPlanteoppstøtting (test)Type">
      <annotation>
         <documentation>13308: Angir hva vegobjektet er festet på.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13308</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Festet på</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:FestetPåPlanteoppstøtting (test)EnumerationType nvdb:FestetPåPlanteoppstøtting (test)OtherType"/>
   </simpleType>
   <simpleType name="FestetPåPlanteoppstøtting (test)EnumerationType">
      <annotation>
         <documentation>13308: Angir hva vegobjektet er festet på.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13308</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Festet på</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="e">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23269</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Egen oppsetting</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="m">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23268</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Mur</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="s">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23267</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Skjerm</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="FestetPåPlanteoppstøtting (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="MaterialePlanteoppstøtting (test)Type">
      <annotation>
         <documentation>13307: Angir materiale.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13307</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Materiale</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:MaterialePlanteoppstøtting (test)EnumerationType nvdb:MaterialePlanteoppstøtting (test)OtherType"/>
   </simpleType>
   <simpleType name="MaterialePlanteoppstøtting (test)EnumerationType">
      <annotation>
         <documentation>13307: Angir materiale.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13307</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Materiale</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="m">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23264</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Metall</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="pk">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23266</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Plast/kompositt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="t">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23265</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Tre</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="MaterialePlanteoppstøtting (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Planteoppstøtting (test)"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Planteoppstøtting (test)Type">
      <annotation>
         <documentation>1011: Innretning som planter kan klatre/støtte seg på.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1011</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Planteoppstøtting (test)</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Planteoppstøtting (test)Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="type" type="nvdb:TypePlanteoppstøtting (test)Type">
                  <annotation>
                     <documentation>13306: Angir hvilken type vegobjektet er av.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13306</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="materiale" type="nvdb:MaterialePlanteoppstøtting (test)Type">
                  <annotation>
                     <documentation>13307: Angir materiale.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13307</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Materiale</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="festetPå">
                  <annotation>
                     <documentation>13308: Angir hva vegobjektet er festet på.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13308</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Festet på</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="høyde" type="double">
                  <annotation>
                     <documentation>13309: Angir egenhøyde av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13309</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Høyde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="lengde" type="double">
                  <annotation>
                     <documentation>13310: Angir lengde på vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13310</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Lengde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="etableringsår" type="integer">
                  <annotation>
                     <documentation>13311: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13311</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="produsent" type="string">
                  <annotation>
                     <documentation>13312: Angir navn på produsent/fabrikant av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13312</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Produsent</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="produktnavn" type="string">
                  <annotation>
                     <documentation>13313: Angir produktnavn for vegobjektet. Produktnavn kan inneholde modellnavn, typebetegnelse, typenummer og ev. serienummer.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13313</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Produktnavn</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>13314: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13314</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="eier"
                        type="nvdb:EierPlanteoppstøtting (test)Type">
                  <annotation>
                     <documentation>13315: Angir hvem som er eier av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13315</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligPlanteoppstøtting (test)Type">
                  <annotation>
                     <documentation>13316: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13316</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>13317: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13317</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded"
                        minOccurs="0"
                        name="lineærPosisjon"
                        type="nvdb:LineærPosisjonPunktPropertyType">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Planteoppstøtting (test)PropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Planteoppstøtting (test)"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="TypePlanteoppstøtting (test)Type">
      <annotation>
         <documentation>13306: Angir hvilken type vegobjektet er av.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13306</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TypePlanteoppstøtting (test)EnumerationType nvdb:TypePlanteoppstøtting (test)OtherType"/>
   </simpleType>
   <simpleType name="TypePlanteoppstøtting (test)EnumerationType">
      <annotation>
         <documentation>13306: Angir hvilken type vegobjektet er av.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13306</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="e">
            <annotation>
               <documentation>23262: Innretning for å feste planter til vegg, benyttes bla på støyskjermer.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23262</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Espalie</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="t">
            <annotation>
               <documentation>23263: Innretning for å beskytte tre/planter mot påkjørsel/skade.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23263</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Trebeskytter</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TypePlanteoppstøtting (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligPlanteoppstøtting (test)Type">
      <annotation>
         <documentation>13316: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13316</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligPlanteoppstøtting (test)EnumerationType nvdb:VedlikeholdsansvarligPlanteoppstøtting (test)OtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligPlanteoppstøtting (test)EnumerationType">
      <annotation>
         <documentation>13316: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13316</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23257</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23259</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23256</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="OPS">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23258</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">OPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23260</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23255</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23261</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligPlanteoppstøtting (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
