<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.44">
   <annotation>
      <documentation>1012: Angir hvilket beredskapsnivå det er på vegstrekningen.  Nivåsetting som metode skal bidra til at veier åpnes raskere etter hendelser som lager blokkering/stans på veinettet over tid. Beredskapsnivå for en vegstrekning fastsettes av vegeier i samråd med Politiet ut fra vurderinger knyttet til:  1. Hvor høy trafikktetthet det er på strekningen. 2. Hvor viktig strekningen er for fremkommelighet for kritisk transport. 3. Hvilke muligheter som finnes for omkjøring. 4. Hvor egnet aktuelle omkjøringsruter er.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="Beredskapsnivå (test)"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Beredskapsnivå (test)Type">
      <annotation>
         <documentation>1012: Angir hvilket beredskapsnivå det er på vegstrekningen.  Nivåsetting som metode skal bidra til at veier åpnes raskere etter hendelser som lager blokkering/stans på veinettet over tid. Beredskapsnivå for en vegstrekning fastsettes av vegeier i samråd med Politiet ut fra vurderinger knyttet til:  1. Hvor høy trafikktetthet det er på strekningen. 2. Hvor viktig strekningen er for fremkommelighet for kritisk transport. 3. Hvilke muligheter som finnes for omkjøring. 4. Hvor egnet aktuelle omkjøringsruter er.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1012</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Beredskapsnivå (test)</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Beredskapsnivå (test)Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="beredskapsnivå"
                        type="nvdb:BeredskapsnivåBeredskapsnivå (test)Type">
                  <annotation>
                     <documentation>13318: Angir beredskapsnivå.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13318</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Beredskapsnivå</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>13319: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13319</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Beredskapsnivå (test)PropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Beredskapsnivå (test)"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="BeredskapsnivåBeredskapsnivå (test)Type">
      <annotation>
         <documentation>13318: Angir beredskapsnivå.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13318</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Beredskapsnivå</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:BeredskapsnivåBeredskapsnivå (test)EnumerationType nvdb:BeredskapsnivåBeredskapsnivå (test)OtherType"/>
   </simpleType>
   <simpleType name="BeredskapsnivåBeredskapsnivå (test)EnumerationType">
      <annotation>
         <documentation>13318: Angir beredskapsnivå.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13318</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Beredskapsnivå</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="gr">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23270</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Grønn</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="gu">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23271</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Gul</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="rø">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23272</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Rød</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="sv">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23273</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Svart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="BeredskapsnivåBeredskapsnivå (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
