<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.45">
   <annotation>
      <documentation>1013: Alle stikkrenner, kulverter og bruer hvor fisken burde kunne passere, uavhengig av om det faktisk skjer. Stikkrenner, kulvert og bruer er typiske tiltak som har primærfunksjon knyttet til vannhåndtering, men som samtidig har sekundærfunksjon som fiskepassasje. Fiskepassasjer kan ha egne tiltak i form av feks vannspeil, kulper, terskler og fisketrapper og som krever særskilt drift og vedlikehold. Driften og vedlikeholdet av fiskepassasjer skal ivareta frie vandringsveger for både fisk og andre ferkvannssorganismer med egen evne til vandring.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="BunnsubstratFiskepassasjeType">
      <annotation>
         <documentation>13342: Beskrivelse av bunnsubstrat i fiskepassasjen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13342</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Bunnsubstrat</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:BunnsubstratFiskepassasjeEnumerationType nvdb:BunnsubstratFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="BunnsubstratFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13342: Beskrivelse av bunnsubstrat i fiskepassasjen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13342</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Bunnsubstrat</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="ng">
            <annotation>
               <documentation>23317: Passasjen har naturlig bekke-, elve- eller innsjøbunn med feks stein, grus, sand, silt, mudder eller fjell i dagen. Bunnen er ikke modifisert av menneskeskapte tiltak og framstår som opprinnelig.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23317</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Naturlig</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="nk">
            <annotation>
               <documentation>23318: Passasjen har delvis naturlig bunn som følge av naturlig eller kunstig tilførsel av naturlige bunnsedimenter. Kunstig tilførsel kan være utplassering av stein og grus for å bedre vandrings- og fiskebiologiske forhold.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23318</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Naturlik</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="un">
            <annotation>
               <documentation>23319: Passasjen har ikke naturlig bunnsubstrat og består typisk av betongplate, plastrør, stålrør, steinheller, pukk og/eller sprengt stein.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23319</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Unaturlig</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="BunnsubstratFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="EierFiskepassasjeType">
      <annotation>
         <documentation>13337: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13337</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EierFiskepassasjeEnumerationType nvdb:EierFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="EierFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13337: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13337</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23299</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23300</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23301</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23298</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23297</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <documentation>23302: Verdi benyttes inntil det er avklart hvem som er eier (ingen verdi tolkes som at vegeier er eier).</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23302</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EierFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Fiskepassasje"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:FiskepassasjeType">
      <annotation>
         <documentation>1013: Alle stikkrenner, kulverter og bruer hvor fisken burde kunne passere, uavhengig av om det faktisk skjer. Stikkrenner, kulvert og bruer er typiske tiltak som har primærfunksjon knyttet til vannhåndtering, men som samtidig har sekundærfunksjon som fiskepassasje. Fiskepassasjer kan ha egne tiltak i form av feks vannspeil, kulper, terskler og fisketrapper og som krever særskilt drift og vedlikehold. Driften og vedlikeholdet av fiskepassasjer skal ivareta frie vandringsveger for både fisk og andre ferkvannssorganismer med egen evne til vandring.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1013</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Fiskepassasje</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="FiskepassasjeType">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="lokalitetsnavn" type="string">
                  <annotation>
                     <documentation>13332: VannforekomstID skal benyttes der det finnes, og navn fra Vann-nett og navn fra SSR kan benyttes. F.eks. "Vømmøla - 777- 777-R".</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13332</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Lokalitetsnavn</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="type" type="nvdb:TypeFiskepassasjeType">
                  <annotation>
                     <documentation>13333: Angir hvilken type utforming passasjen har.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13333</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="beskrivelse" type="string">
                  <annotation>
                     <documentation>13334: Beskrivelse av fiskepassasjen og område rundt, referanser til undersøkelser, saksarkiv m.m.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13334</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Beskrivelse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="vandringshinder" type="nvdb:VandringshinderFiskepassasjeType">
                  <annotation>
                     <documentation>13339: Angir om passasje er vandringshindrende for fisk og ferskvannsorganismer.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13339</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vandringshinder</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="beskrivelseVandringshinder" type="string">
                  <annotation>
                     <documentation>13340: Beskrive hva som forårsaker vandringshinder; Høydeforskjell ved utløp, mangler kulp nedstrøms, vannhastighet, hinder eller gitter ved inntak, annet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13340</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Beskrivelse vandringshinder</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="rapportreferanse" type="string">
                  <annotation>
                     <documentation>13409: Angir referanse til rapport som omhandler gitt fiskepassasje.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13409</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Rapportreferanse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tiltaksbehovPrioritering">
                  <annotation>
                     <documentation>13341: Vegeiers egen prioritering av tiltak for denne fiskepassasjen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13341</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tiltaksbehov prioritering</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="bunnsubstrat"
                        type="nvdb:BunnsubstratFiskepassasjeType">
                  <annotation>
                     <documentation>13342: Beskrivelse av bunnsubstrat i fiskepassasjen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13342</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Bunnsubstrat</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="tiltakstype"
                        type="nvdb:TiltakstypeFiskepassasjeType">
                  <annotation>
                     <documentation>13343: Hovedtiltak for å sikre fiskens frie vandring. Øvrige tiltak beskrives i egenskapstype "Beskrivelse tiltak" (13345).</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13343</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tiltakstype</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="statusTiltak">
                  <annotation>
                     <documentation>13344: Angir status for tiltak.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13344</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Status tiltak</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="beskrivelseTiltak" type="string">
                  <annotation>
                     <documentation>13345: Opplisting av både hovedtiltak og øvrige tiltak.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13345</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Beskrivelse tiltak</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="brutus_Id" type="string">
                  <annotation>
                     <documentation>13335: Gir referanse til brudatabanken.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13335</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Brutus_Id</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tiltaksår" type="integer">
                  <annotation>
                     <documentation>13346: Angir hvilket år det ble gjennomført tiltak for å sikre fiskens frie vandring.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13346</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tiltaksår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="befaringsår" type="integer">
                  <annotation>
                     <documentation>13347: Angir hvilket år det ble sist gjennomført befaring og vurdering av fiskepassasjens tilstand.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13347</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Befaringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="eier" type="nvdb:EierFiskepassasjeType">
                  <annotation>
                     <documentation>13337: Angir hvem som er eier av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13337</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligFiskepassasjeType">
                  <annotation>
                     <documentation>13338: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13338</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>13348: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13348</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="senterlinje" type="gml:CurvePropertyType">
                  <annotation>
                     <documentation>13350: Gir linje/kurve som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13350</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, linje</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="område" type="gml:SurfacePropertyType">
                  <annotation>
                     <documentation>13349: Gir flate/polygon som geometrisk avgrenser området.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13349</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, flate</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="etableringsår" type="integer">
                  <annotation>
                     <documentation>13336: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13336</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded"
                        minOccurs="0"
                        name="lineærPosisjon"
                        type="nvdb:LineærPosisjonPunktPropertyType">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="FiskepassasjePropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Fiskepassasje"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="StatusTiltakFiskepassasjeType">
      <annotation>
         <documentation>13344: Angir status for tiltak.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13344</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Status tiltak</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:StatusTiltakFiskepassasjeEnumerationType nvdb:StatusTiltakFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="StatusTiltakFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13344: Angir status for tiltak.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13344</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Status tiltak</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="iu">
            <annotation>
               <documentation>23329: Tiltak identifisert men ikke gjennomført.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23329</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ikke utført</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ut">
            <annotation>
               <documentation>23328: Tiltak som er gjennomført.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23328</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Utført</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="u">
            <annotation>
               <documentation>23330: Status er ukjent.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23330</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ukjent</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="StatusTiltakFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="TiltaksbehovPrioriteringFiskepassasjeType">
      <annotation>
         <documentation>13341: Vegeiers egen prioritering av tiltak for denne fiskepassasjen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13341</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tiltaksbehov prioritering</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TiltaksbehovPrioriteringFiskepassasjeEnumerationType nvdb:TiltaksbehovPrioriteringFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="TiltaksbehovPrioriteringFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13341: Vegeiers egen prioritering av tiltak for denne fiskepassasjen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13341</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tiltaksbehov prioritering</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="1">
            <annotation>
               <documentation>23314: Høy prioritet - lavthengende frukter, viktige fiskesamfunn, restaureringsprosjekter, etc.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23314</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">1</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="2">
            <annotation>
               <documentation>23315: Lav prioritet.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23315</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">2</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="3">
            <annotation>
               <documentation>23316: Ikke prioritert.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23316</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">3</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TiltaksbehovPrioriteringFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="TiltakstypeFiskepassasjeType">
      <annotation>
         <documentation>13343: Hovedtiltak for å sikre fiskens frie vandring. Øvrige tiltak beskrives i egenskapstype "Beskrivelse tiltak" (13345).</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13343</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tiltakstype</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TiltakstypeFiskepassasjeEnumerationType nvdb:TiltakstypeFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="TiltakstypeFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13343: Hovedtiltak for å sikre fiskens frie vandring. Øvrige tiltak beskrives i egenskapstype "Beskrivelse tiltak" (13345).</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13343</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tiltakstype</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="an">
            <annotation>
               <documentation>23325: Annet hovedtiltak. "Beskrivelse tiltak" kan benyttes for å beskrive hva som er gjennomført av tiltak.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23325</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="bpl">
            <annotation>
               <documentation>23321: Plasstøpte betongterskler.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23321</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Betongterskler, plasstøpt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="bp">
            <annotation>
               <documentation>23320: Betongterskler som del av betongrør eller ettermonterte prefabrikerte betongterskler.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23320</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Betongterskler, prefabrikert</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ft">
            <annotation>
               <documentation>23348: Passasje via fisketrapp i vannforekomsten som er tilknyttet veganlegget like opp- eller nedstrøms stikkrenne/kulvert/bru.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23348</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fisketrapp</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ft">
            <annotation>
               <documentation>23322: Fleksiterskler, baffles, mm.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23322</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fleksiterskler</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="os">
            <annotation>
               <documentation>23323: Ospestokker montert mot kulvertbunn.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23323</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ospestokker</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="tn">
            <annotation>
               <documentation>23324: Heving av vannspeil med terskler inn mot utløp stikkrenne/kulvert for å utligne fritt fall og senke vannhastighet.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23324</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Terskler nedstrøms</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ut">
            <annotation>
               <documentation>23326: Utplassering av stein eller annet naturtypisk substrat.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23326</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Utlegging av substrat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ia">
            <annotation>
               <documentation>23327: Ikke behov for tiltak for å sikre fiskens frie vandring.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23327</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ikke aktuell</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TiltakstypeFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="TypeFiskepassasjeType">
      <annotation>
         <documentation>13333: Angir hvilken type utforming passasjen har.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13333</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TypeFiskepassasjeEnumerationType nvdb:TypeFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="TypeFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13333: Angir hvilken type utforming passasjen har.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13333</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="b">
            <annotation>
               <documentation>23336: Passasje der fisk vandrer under åpen brukonstruksjon.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23336</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Bru</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="kv">
            <annotation>
               <documentation>23335: Passasje der fisk vandrer gjennom kulvert.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23335</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kulvert</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="sr">
            <annotation>
               <documentation>23334: Passasje der fisk vandrer gjennom stikkrenne.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23334</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stikkrenne</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="a">
            <annotation>
               <documentation>23338: Alle andre typer. Beskrives under Beskrivelse.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23338</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ft">
            <annotation>
               <documentation>23337: Passasje via fisketrapp i vannforekomsten som er tilknyttet veganlegget like opp- eller nedstrøms stikkrenne/kulvert/bru.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23337</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fisketrapp</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TypeFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VandringshinderFiskepassasjeType">
      <annotation>
         <documentation>13339: Angir om passasje er vandringshindrende for fisk og ferskvannsorganismer.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13339</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vandringshinder</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VandringshinderFiskepassasjeEnumerationType nvdb:VandringshinderFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="VandringshinderFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13339: Angir om passasje er vandringshindrende for fisk og ferskvannsorganismer.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13339</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vandringshinder</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="jf">
            <annotation>
               <documentation>23310: Dokumentert menneskapt vandringshinder med tiltaksbehov for å sikre fiskens frie vandring.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23310</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Sperre, nær absolutt hinder</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="u">
            <annotation>
               <documentation>23313: Angis der det mangler kunnskap om hvorvidt fiskepassasjen er vandringshindrende.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23313</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ukjent</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <documentation>23312: Dersom det finnes kunnskap som bekrefter at passasjen ikke har noen form for menneskeskapte vandringshindre og/eller der det er dokumentert at det gjennomført varig tiltak som sikrer fiskens frie vandring. Omfatter også naturlige vandringshindre.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23312</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Vandring påvirkes ikke eller kun i beskjeden grad</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="jd">
            <annotation>
               <documentation>23311: Dersom det er dokumentert at passasjen har menneskeskapt vandringshinder for enkelte arter, års- eller størrelsesklasser av fisk eller andre ferskvannsorganismer. Ikke akutt tiltaksbehov, men det må tas hensyn ved neste skifte av rør, kulvert eller bru.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23311</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Vandring påvirkes, delvis hinder</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VandringshinderFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligFiskepassasjeType">
      <annotation>
         <documentation>13338: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13338</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligFiskepassasjeEnumerationType nvdb:VedlikeholdsansvarligFiskepassasjeOtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligFiskepassasjeEnumerationType">
      <annotation>
         <documentation>13338: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13338</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23305</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23307</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23304</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="OPS">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23306</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">OPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23308</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23303</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23309</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligFiskepassasjeOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
