<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.44">
   <annotation>
      <documentation>1014: Beredskapsstrekning.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="Beredskapsstrekning (test)"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Beredskapsstrekning (test)Type">
      <annotation>
         <documentation>1014: Beredskapsstrekning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1014</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Beredskapsstrekning (test)</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Beredskapsstrekning (test)Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="nummer" type="integer">
                  <annotation>
                     <documentation>13359: Gir nummer på beredskapsstrekningen. Nummer benyttes som nøkkelfelt mot informasjon i andre system.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13359</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Nummer</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="navn" type="string">
                  <annotation>
                     <documentation>13361: Gir navn på strekning</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13361</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Navn</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="beskrivelse" type="string">
                  <annotation>
                     <documentation>13364: Beskrivelse av strekning</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13364</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Beskrivelse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Beredskapsstrekning (test)PropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Beredskapsstrekning (test)"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
</schema>
