<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.44">
   <annotation>
      <documentation>1015: Beredskapsdelstrekning.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="Beredskapsdelstrekning (test)"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Beredskapsdelstrekning (test)Type">
      <annotation>
         <documentation>1015: Beredskapsdelstrekning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1015</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Beredskapsdelstrekning (test)</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Beredskapsdelstrekning (test)Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="nummerStrekning" type="integer">
                  <annotation>
                     <documentation>13360: Gir nummer på beredskapsstrekningen som delstrekningen er del av.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13360</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Nummer strekning</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="navnDelstrekning" type="string">
                  <annotation>
                     <documentation>13362: Gir navn på delstrekning</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13362</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Navn delstrekning</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="beskrivelse" type="string">
                  <annotation>
                     <documentation>13363: Beskrivelse av hovedutfordring på strekningen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13363</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Beskrivelse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="envegsTransport">
                  <annotation>
                     <documentation>13365: Angir om dimensjonerende kjøreboks kan passere om alle kjørefelt benyttes.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13365</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Envegs transport</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tiltakEnvegsTransport" type="string">
                  <annotation>
                     <documentation>13366: Beskrivelse av hvilke tiltak må gjennomføres for å oppnå envegs transport.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13366</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tiltak envegs transport</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tiltakTovegsTransport" type="string">
                  <annotation>
                     <documentation>13367: Beskrivelse av hvilke tiltak som må gjennomføres for å oppnå tovegs transport.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13367</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tiltak tovegs transport</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Beredskapsdelstrekning (test)PropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Beredskapsdelstrekning (test)"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="EnvegsTransportBeredskapsdelstrekning (test)Type">
      <annotation>
         <documentation>13365: Angir om dimensjonerende kjøreboks kan passere om alle kjørefelt benyttes.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13365</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Envegs transport</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EnvegsTransportBeredskapsdelstrekning (test)EnumerationType nvdb:EnvegsTransportBeredskapsdelstrekning (test)OtherType"/>
   </simpleType>
   <simpleType name="EnvegsTransportBeredskapsdelstrekning (test)EnumerationType">
      <annotation>
         <documentation>13365: Angir om dimensjonerende kjøreboks kan passere om alle kjørefelt benyttes.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13365</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Envegs transport</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <documentation>23343: Det er mulig å passere om en benytter alle kjørefelt.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23343</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <documentation>23344: Det er ikke mulig å passere selv om en benytter alle kjørefelt.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23344</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EnvegsTransportBeredskapsdelstrekning (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
