<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.44">
   <annotation>
      <documentation>1016: Punkt som er tilrettelagt for kryssing av kjøreveg for myke trafikanter, uten at gangfelt er anlagt. (Kilde: Felles definisjonsliste for Håndbøkene)</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="BelysningTilrettelagt kryssing (test)Type">
      <annotation>
         <documentation>13372: Angir om tilrettelagt krysning er belyst. Kan være fra egen belysning eller fra generell veg-/gatebelysning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13372</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Belysning</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:BelysningTilrettelagt kryssing (test)EnumerationType nvdb:BelysningTilrettelagt kryssing (test)OtherType"/>
   </simpleType>
   <simpleType name="BelysningTilrettelagt kryssing (test)EnumerationType">
      <annotation>
         <documentation>13372: Angir om tilrettelagt krysning er belyst. Kan være fra egen belysning eller fra generell veg-/gatebelysning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13372</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Belysning</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23408</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23409</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="BelysningTilrettelagt kryssing (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="EierTilrettelagt kryssing (test)Type">
      <annotation>
         <documentation>13376: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13376</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EierTilrettelagt kryssing (test)EnumerationType nvdb:EierTilrettelagt kryssing (test)OtherType"/>
   </simpleType>
   <simpleType name="EierTilrettelagt kryssing (test)EnumerationType">
      <annotation>
         <documentation>13376: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13376</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23351</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23352</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23353</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23350</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23349</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <documentation>23354: Verdi benyttes inntil det er avklart hvem som er eier (ingen verdi tolkes som at vegeier er eier).</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23354</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EierTilrettelagt kryssing (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="NedsenkaKantsteinTilrettelagt kryssing (test)Type">
      <annotation>
         <documentation>13379: Angir om det er nedsenka kantstein.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13379</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Nedsenka kantstein</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:NedsenkaKantsteinTilrettelagt kryssing (test)EnumerationType nvdb:NedsenkaKantsteinTilrettelagt kryssing (test)OtherType"/>
   </simpleType>
   <simpleType name="NedsenkaKantsteinTilrettelagt kryssing (test)EnumerationType">
      <annotation>
         <documentation>13379: Angir om det er nedsenka kantstein.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13379</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Nedsenka kantstein</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="ik">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23364</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ikke kantstein</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="J">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23362</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23363</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="NedsenkaKantsteinTilrettelagt kryssing (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Tilrettelagt kryssing (test)"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Tilrettelagt kryssing (test)Type">
      <annotation>
         <documentation>1016: Punkt som er tilrettelagt for kryssing av kjøreveg for myke trafikanter, uten at gangfelt er anlagt. (Kilde: Felles definisjonsliste for Håndbøkene)</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1016</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tilrettelagt kryssing (test)</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Tilrettelagt kryssing (test)Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element minOccurs="0" name="stedsangivelse" type="string">
                  <annotation>
                     <documentation>13371: Stedsnavn hvor forekomst er lokalisert. Kan eventuelt gi plassering relatert til stedsnavn. I kryssområder der det er flere tilrettelagte krysninger kan de enkelte gis en forløpende nummerering i tillegg til stedsnavnet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13371</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Stedsangivelse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="belysning" type="nvdb:BelysningTilrettelagt kryssing (test)Type">
                  <annotation>
                     <documentation>13372: Angir om tilrettelagt krysning er belyst. Kan være fra egen belysning eller fra generell veg-/gatebelysning.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13372</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Belysning</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="trafikkøy"
                        type="nvdb:TrafikkøyTilrettelagt kryssing (test)Type">
                  <annotation>
                     <documentation>13373: Angir om det er trafikkøy i tilrettelagt krysning.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13373</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Trafikkøy</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="nedsenkaKantstein">
                  <annotation>
                     <documentation>13379: Angir om det er nedsenka kantstein.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13379</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Nedsenka kantstein</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="etableringsår" type="integer">
                  <annotation>
                     <documentation>13374: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13374</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>13375: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13375</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="eier"
                        type="nvdb:EierTilrettelagt kryssing (test)Type">
                  <annotation>
                     <documentation>13376: Angir hvem som er eier av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13376</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligTilrettelagt kryssing (test)Type">
                  <annotation>
                     <documentation>13377: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13377</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="område" type="gml:SurfacePropertyType">
                  <annotation>
                     <documentation>13378: Gir flate/polygon som geometrisk avgrenser objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13378</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, flate</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Tilrettelagt kryssing (test)PropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Tilrettelagt kryssing (test)"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="TrafikkøyTilrettelagt kryssing (test)Type">
      <annotation>
         <documentation>13373: Angir om det er trafikkøy i tilrettelagt krysning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13373</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Trafikkøy</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TrafikkøyTilrettelagt kryssing (test)EnumerationType nvdb:TrafikkøyTilrettelagt kryssing (test)OtherType"/>
   </simpleType>
   <simpleType name="TrafikkøyTilrettelagt kryssing (test)EnumerationType">
      <annotation>
         <documentation>13373: Angir om det er trafikkøy i tilrettelagt krysning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13373</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Trafikkøy</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23410</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23411</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TrafikkøyTilrettelagt kryssing (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTilrettelagt kryssing (test)Type">
      <annotation>
         <documentation>13377: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13377</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligTilrettelagt kryssing (test)EnumerationType nvdb:VedlikeholdsansvarligTilrettelagt kryssing (test)OtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTilrettelagt kryssing (test)EnumerationType">
      <annotation>
         <documentation>13377: Angir hvem som er ansvarlig for vedlikehold av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13377</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23361</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23356</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23359</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="OPS">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23360</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">OPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23357</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23355</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23358</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTilrettelagt kryssing (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
