<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.44">
   <annotation>
      <documentation>1017: Turistvegattraksjon</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="EgenInstruksForDriftOgVedlikeholdTuristvegattraksjon (test)Type">
      <annotation>
         <documentation>13385: Angir om det finnes egen instruks for drift og vedlikehold.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13385</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Egen instruks for drift og vedlikehold</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EgenInstruksForDriftOgVedlikeholdTuristvegattraksjon (test)EnumerationType nvdb:EgenInstruksForDriftOgVedlikeholdTuristvegattraksjon (test)OtherType"/>
   </simpleType>
   <simpleType name="EgenInstruksForDriftOgVedlikeholdTuristvegattraksjon (test)EnumerationType">
      <annotation>
         <documentation>13385: Angir om det finnes egen instruks for drift og vedlikehold.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13385</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Egen instruks for drift og vedlikehold</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23383</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23384</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EgenInstruksForDriftOgVedlikeholdTuristvegattraksjon (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="EierTuristvegattraksjon (test)Type">
      <annotation>
         <documentation>13388: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13388</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EierTuristvegattraksjon (test)EnumerationType nvdb:EierTuristvegattraksjon (test)OtherType"/>
   </simpleType>
   <simpleType name="EierTuristvegattraksjon (test)EnumerationType">
      <annotation>
         <documentation>13388: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13388</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23392</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23390</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23391</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23394</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23389</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <documentation>23393: Verdi benyttes inntil det er avklart hvem som er eier (ingen verdi tolkes som at vegeier er eier).</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23393</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EierTuristvegattraksjon (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="NavnPåTuristvegruteTuristvegattraksjon (test)Type">
      <annotation>
         <documentation>13381: Angir navn på turistveg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13381</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Navn på turistvegrute</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:NavnPåTuristvegruteTuristvegattraksjon (test)EnumerationType nvdb:NavnPåTuristvegruteTuristvegattraksjon (test)OtherType"/>
   </simpleType>
   <simpleType name="NavnPåTuristvegruteTuristvegattraksjon (test)EnumerationType">
      <annotation>
         <documentation>13381: Angir navn på turistveg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13381</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Navn på turistvegrute</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="an">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23368</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Andøya</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="at">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23371</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Atlanterhavsvegen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="au">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23378</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Aurlandsfjellet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="gs">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23373</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Gamle Strynefjellsvegen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ga">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23377</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Gaulafjellet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="gt">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23372</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Geiranger - Trollstigen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ha">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23379</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Hardanger</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="hv">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23380</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Hardangervidda</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="hø">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23366</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Havøysund</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="he">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23370</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Helgelandskysten</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="jæ">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23382</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Jæren</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="lo">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23369</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Lofoten</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ro">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23374</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Rondane</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ry">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23381</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ryfylke</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="se">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23367</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Senja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="so">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23375</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Sognefjellet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="vf">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23376</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Valdresflye</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="va">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23365</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Varanger</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="NavnPåTuristvegruteTuristvegattraksjon (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Turistvegattraksjon (test)"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Turistvegattraksjon (test)Type">
      <annotation>
         <documentation>1017: Turistvegattraksjon</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1017</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Turistvegattraksjon (test)</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Turistvegattraksjon (test)Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="navnPåAttraksjon" type="string">
                  <annotation>
                     <documentation>13380: Angir navn på attraksjon.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13380</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Navn på attraksjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="navnPåTuristvegrute">
                  <annotation>
                     <documentation>13381: Angir navn på turistveg.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13381</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Navn på turistvegrute</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="type" type="nvdb:TypeTuristvegattraksjon (test)Type">
                  <annotation>
                     <documentation>13382: Angir type.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13382</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="beskrivelse" type="string">
                  <annotation>
                     <documentation>13391: Beskrivelse av turistvegattraksjonen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13391</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Beskrivelse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="lenkeTilInformasjon" type="string">
                  <annotation>
                     <documentation>13383: Angir lenke til informasjon.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13383</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Lenke til informasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="merknadDrift" type="string">
                  <annotation>
                     <documentation>13384: Angir merknad for drift.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13384</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Merknad drift</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="egenInstruksForDriftOgVedlikehold">
                  <annotation>
                     <documentation>13385: Angir om det finnes egen instruks for drift og vedlikehold.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13385</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Egen instruks for drift og vedlikehold</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="etableringsår" type="integer">
                  <annotation>
                     <documentation>13386: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13386</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>13387: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13387</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="eier"
                        type="nvdb:EierTuristvegattraksjon (test)Type">
                  <annotation>
                     <documentation>13388: Angir hvem som er eier av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13388</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligTuristvegattraksjon (test)Type">
                  <annotation>
                     <documentation>13389: Angir hvem som er vedlikeholdsansvarlig for turistvegattraksjonen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13389</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>13390: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13390</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded"
                        minOccurs="0"
                        name="lineærPosisjon"
                        type="nvdb:LineærPosisjonPunktPropertyType">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Turistvegattraksjon (test)PropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Turistvegattraksjon (test)"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="TypeTuristvegattraksjon (test)Type">
      <annotation>
         <documentation>13382: Angir type.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13382</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TypeTuristvegattraksjon (test)EnumerationType nvdb:TypeTuristvegattraksjon (test)OtherType"/>
   </simpleType>
   <simpleType name="TypeTuristvegattraksjon (test)EnumerationType">
      <annotation>
         <documentation>13382: Angir type.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13382</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="ko">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23388</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommersielt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="na">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23385</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nasjonal attraksjon</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="sm">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23387</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Småstopp</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="tp">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23386</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Turistvegpunkt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TypeTuristvegattraksjon (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTuristvegattraksjon (test)Type">
      <annotation>
         <documentation>13389: Angir hvem som er vedlikeholdsansvarlig for turistvegattraksjonen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13389</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligTuristvegattraksjon (test)EnumerationType nvdb:VedlikeholdsansvarligTuristvegattraksjon (test)OtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTuristvegattraksjon (test)EnumerationType">
      <annotation>
         <documentation>13389: Angir hvem som er vedlikeholdsansvarlig for turistvegattraksjonen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13389</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23401</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23396</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23399</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="OPS">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23400</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">OPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23397</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23395</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23398</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTuristvegattraksjon (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
