<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.45">
   <annotation>
      <documentation>1019: Sykkelrasteplass er et tilrettelagt stoppested primært for syklister og gående, og som ikke tilfredsstiller kravene til en skiltet rasteplass langs bilveg. Her kan en ta en pause, hvile og parkere sykkelen. Rasteplass for gående og syklende skal ha sitteplasser og plass til å parkere sykler. Sykkelrasteplass skal være adskilt fra bilveg.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="DrikkevannSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13443: Angir om det er drikkevann på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13443</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Drikkevann</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:DrikkevannSykkelrasteplass (test)EnumerationType nvdb:DrikkevannSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="DrikkevannSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13443: Angir om det er drikkevann på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13443</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Drikkevann</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23542</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23543</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="DrikkevannSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="DusjSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13431: Angir om det er dusj på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13431</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Dusj</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:DusjSykkelrasteplass (test)EnumerationType nvdb:DusjSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="DusjSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13431: Angir om det er dusj på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13431</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Dusj</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="JaIkkeTi">
            <annotation>
               <documentation>23521: Angir at rasteplassen har dusj, men at denne ikke er tilpasset bevegelseshemmede.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23521</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja, ikke tilpasset bevegelseshemmede</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="JaTilpas">
            <annotation>
               <documentation>23520: Angir at rasteplassen har dusj, og at denne er tilpasset bevegelseshemmede.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23520</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja, tilpasset bevegelseshemmede</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <documentation>23522: Angir at rasteplassen ikke har dusj.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23522</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="DusjSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="EierSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13439: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13439</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EierSykkelrasteplass (test)EnumerationType nvdb:EierSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="EierSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13439: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13439</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23537</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23535</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23536</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23539</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23534</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <documentation>23538: Verdi benyttes inntil det er avklart hvem som er eier (ingen verdi tolkes som at vegeier er eier).</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23538</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EierSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="FastDekkeSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13434: Angir om det er fast dekke på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13434</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Fast dekke</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:FastDekkeSykkelrasteplass (test)EnumerationType nvdb:FastDekkeSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="FastDekkeSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13434: Angir om det er fast dekke på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13434</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Fast dekke</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23525</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23526</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="FastDekkeSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="OppbevaringsskapSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13445: Angir at sykkelrasteplassen har oppbevaringsskap tilgjengelig for besøkende.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13445</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Oppbevaringsskap</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:OppbevaringsskapSykkelrasteplass (test)EnumerationType nvdb:OppbevaringsskapSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="OppbevaringsskapSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13445: Angir at sykkelrasteplassen har oppbevaringsskap tilgjengelig for besøkende.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13445</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Oppbevaringsskap</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="ji">
            <annotation>
               <documentation>23545: Angir at sykkelrasteplassen har oppbevaringsskap tilgjengelig for besøkende. Det er ikke mulig å låse disse skapene.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23545</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja, ikke låsbart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="jl">
            <annotation>
               <documentation>23544: Angir at sykkelrasteplassen har låsbare oppbevaringsskap tilgjengelig for besøkende.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23544</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja, låsbart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <documentation>23546: Angir at sykkelrasteplassen ikke har oppbevaringsskap tilgjengelig for besøkende.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23546</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="OppbevaringsskapSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="StrømuttakSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13432: Angir om det er strømuttak i tilknytning til servicebygg eller toalettanlegg tilgjengelig for besøkende.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13432</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Strømuttak</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:StrømuttakSykkelrasteplass (test)EnumerationType nvdb:StrømuttakSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="StrømuttakSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13432: Angir om det er strømuttak i tilknytning til servicebygg eller toalettanlegg tilgjengelig for besøkende.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13432</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Strømuttak</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23523</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23524</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="StrømuttakSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Sykkelrasteplass (test)"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Sykkelrasteplass (test)Type">
      <annotation>
         <documentation>1019: Sykkelrasteplass er et tilrettelagt stoppested primært for syklister og gående, og som ikke tilfredsstiller kravene til en skiltet rasteplass langs bilveg. Her kan en ta en pause, hvile og parkere sykkelen. Rasteplass for gående og syklende skal ha sitteplasser og plass til å parkere sykler. Sykkelrasteplass skal være adskilt fra bilveg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1019</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Sykkelrasteplass (test)</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Sykkelrasteplass (test)Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element minOccurs="0" name="navn" type="string">
                  <annotation>
                     <documentation>13430: Angir navn på sykkelrasteplassen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13430</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Navn</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="takoverbygg" type="nvdb:TakoverbyggSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13442: Angir om det er mulighet for tak over hodet ved opphold på sykkelrasteplassen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13442</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Takoverbygg</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="drikkevann" type="nvdb:DrikkevannSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13443: Angir om det er drikkevann på sykkelrasteplassen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13443</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Drikkevann</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="dusj" type="nvdb:DusjSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13431: Angir om det er dusj på sykkelrasteplassen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13431</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Dusj</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="strømuttak" type="nvdb:StrømuttakSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13432: Angir om det er strømuttak i tilknytning til servicebygg eller toalettanlegg tilgjengelig for besøkende.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13432</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Strømuttak</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="sykkelservice"
                        type="nvdb:SykkelserviceSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13444: Angir at sykkelrasteplassen har sykkelpumper og/eller verktøy tilgjengelig for besøkende.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13444</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Sykkelservice</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="oppbevaringsskap"
                        type="nvdb:OppbevaringsskapSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13445: Angir at sykkelrasteplassen har oppbevaringsskap tilgjengelig for besøkende.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13445</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Oppbevaringsskap</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="areal_Totalt" type="integer">
                  <annotation>
                     <documentation>13433: Angir totalt areal av sykkelrasteplassen. For mer informasjon om ulike arealtyper henvises til aktuelle "datterobjekt".</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13433</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Areal, totalt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="fastDekke">
                  <annotation>
                     <documentation>13434: Angir om det er fast dekke på sykkelrasteplassen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13434</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Fast dekke</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="etableringsår" type="integer">
                  <annotation>
                     <documentation>13435: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13435</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>13436: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13436</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="prosjektreferanse" type="string">
                  <annotation>
                     <documentation>13438: Referanse til prosjekt. Det benyttes samme prosjektreferanse som på tilhørende Veganlegg (VT30). Benyttes for lettere å kunne skille nye data fra eksisterende data i NVDB.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13438</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Prosjektreferanse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="prosjektInternObjekt_ID" type="string">
                  <annotation>
                     <documentation>13437: Objektmerking. Unik innenfor tilhørende vegprosjekt.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13437</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">ProsjektInternObjekt_ID</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="eier"
                        type="nvdb:EierSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13439: Angir hvem som er eier av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13439</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligSykkelrasteplass (test)Type">
                  <annotation>
                     <documentation>13440: Angir hvem som er vedlikeholdsansvarlig for rasteplassen som helhet. Det kan alternativt gis informasjon om dette til de ulike bestanddelene på rasteplassen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13440</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="område" type="gml:SurfacePropertyType">
                  <annotation>
                     <documentation>13441: Gir flate/polygon som geometrisk avgrenser rasteplassen, inkluderer både kjørbart og ikke kjørbart areal.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13441</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, flate</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Sykkelrasteplass (test)PropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Sykkelrasteplass (test)"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="SykkelserviceSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13444: Angir at sykkelrasteplassen har sykkelpumper og/eller verktøy tilgjengelig for besøkende.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13444</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Sykkelservice</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:SykkelserviceSykkelrasteplass (test)EnumerationType nvdb:SykkelserviceSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="SykkelserviceSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13444: Angir at sykkelrasteplassen har sykkelpumper og/eller verktøy tilgjengelig for besøkende.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13444</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Sykkelservice</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23593</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23594</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="SykkelserviceSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="TakoverbyggSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13442: Angir om det er mulighet for tak over hodet ved opphold på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13442</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Takoverbygg</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TakoverbyggSykkelrasteplass (test)EnumerationType nvdb:TakoverbyggSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="TakoverbyggSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13442: Angir om det er mulighet for tak over hodet ved opphold på sykkelrasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13442</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Takoverbygg</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23540</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23541</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TakoverbyggSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligSykkelrasteplass (test)Type">
      <annotation>
         <documentation>13440: Angir hvem som er vedlikeholdsansvarlig for rasteplassen som helhet. Det kan alternativt gis informasjon om dette til de ulike bestanddelene på rasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13440</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligSykkelrasteplass (test)EnumerationType nvdb:VedlikeholdsansvarligSykkelrasteplass (test)OtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligSykkelrasteplass (test)EnumerationType">
      <annotation>
         <documentation>13440: Angir hvem som er vedlikeholdsansvarlig for rasteplassen som helhet. Det kan alternativt gis informasjon om dette til de ulike bestanddelene på rasteplassen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13440</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23533</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23528</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23531</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="OPS">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23532</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">OPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23529</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23527</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23530</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligSykkelrasteplass (test)OtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
