<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.45">
   <annotation>
      <documentation>638: Trafikkstasjon.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="RegionTrafikkstasjonType">
      <annotation>
         <documentation>5864: Region</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">5864</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Region</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:RegionTrafikkstasjonEnumerationType nvdb:RegionTrafikkstasjonOtherType"/>
   </simpleType>
   <simpleType name="RegionTrafikkstasjonEnumerationType">
      <annotation>
         <documentation>5864: Region</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">5864</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Region</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="m">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">8333</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Midt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">8332</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nord</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="s">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">8335</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Sør</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="v">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">8334</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Vest</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="o">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">8336</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Øst</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="RegionTrafikkstasjonOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Trafikkstasjon"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:TrafikkstasjonType">
      <annotation>
         <documentation>638: Trafikkstasjon.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">638</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Trafikkstasjon</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="TrafikkstasjonType">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="navn" type="string">
                  <annotation>
                     <documentation>5872: Gir navn.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5872</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Navn</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="linkTilInfosider" type="string">
                  <annotation>
                     <documentation>5865: Link til infosider.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5865</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Link til infosider</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>11633: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">11633</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>5866: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5866</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="region" type="nvdb:RegionTrafikkstasjonType">
                  <annotation>
                     <documentation>5864: Region</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5864</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Region</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="besøksadresse" type="string">
                  <annotation>
                     <documentation>5871: Gir besøksadresse</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5871</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Besøksadresse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="postadresse" type="string">
                  <annotation>
                     <documentation>5870: Gir postadresse</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5870</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Postadresse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="E_Post" type="string">
                  <annotation>
                     <documentation>5869: E-post - adresse</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5869</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">E-post</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="telefonnummer" type="string">
                  <annotation>
                     <documentation>5868: Telefonnummer</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5868</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Telefonnummer</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="telefaksnummer" type="string">
                  <annotation>
                     <documentation>5867: Telefaksnummer</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5867</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Telefaksnummer</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="byggeår" type="integer">
                  <annotation>
                     <documentation>10380: Angir byggeår for vegobjektet</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10380</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Byggeår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligTrafikkstasjonType">
                  <annotation>
                     <documentation>8122: Angir hvem som er ansvarlig for vedlikehold</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">8122</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="område" type="gml:SurfacePropertyType">
                  <annotation>
                     <documentation>8904: Gir flate/polygon som geometrisk avgrenser området</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">8904</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, flate</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded"
                        minOccurs="0"
                        name="lineærPosisjon"
                        type="nvdb:LineærPosisjonPunktPropertyType">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="TrafikkstasjonPropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Trafikkstasjon"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="VedlikeholdsansvarligTrafikkstasjonType">
      <annotation>
         <documentation>8122: Angir hvem som er ansvarlig for vedlikehold</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">8122</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligTrafikkstasjonEnumerationType nvdb:VedlikeholdsansvarligTrafikkstasjonOtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTrafikkstasjonEnumerationType">
      <annotation>
         <documentation>8122: Angir hvem som er ansvarlig for vedlikehold</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">8122</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">10594</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">10672</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SvV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">10516</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTrafikkstasjonOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
