<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.45">
   <annotation>
      <documentation>69: Byggverk som benyttes i endene av fjelltunnelene for å beskytte tunnelåpning mot rennende vann og fallende snø, is stein og jord. (HB V440).</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="BærerTrafikklastTunnelportalType">
      <annotation>
         <documentation>12978: Angir om tunnelportal skal kunne bære trafikklast. Dette er tilfelle når det går en kryssende veg over tunnelportalen på tvers av hovedvegen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12978</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Bærer trafikklast</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:BærerTrafikklastTunnelportalEnumerationType nvdb:BærerTrafikklastTunnelportalOtherType"/>
   </simpleType>
   <simpleType name="BærerTrafikklastTunnelportalEnumerationType">
      <annotation>
         <documentation>12978: Angir om tunnelportal skal kunne bære trafikklast. Dette er tilfelle når det går en kryssende veg over tunnelportalen på tvers av hovedvegen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12978</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Bærer trafikklast</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <documentation>22538: Tunnelportal bærer trafikklast</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22538</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <documentation>22539: Tunnel bærer ikke trafikklast.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22539</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="BærerTrafikklastTunnelportalOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="TilkomstOvenfraTunnelportalType">
      <annotation>
         <documentation>3099: Angir om det er tilkomst ovenfra til tunnelportal. (opprinnelig fradato: 20040421)</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">3099</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tilkomst ovenfra</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TilkomstOvenfraTunnelportalEnumerationType nvdb:TilkomstOvenfraTunnelportalOtherType"/>
   </simpleType>
   <simpleType name="TilkomstOvenfraTunnelportalEnumerationType">
      <annotation>
         <documentation>3099: Angir om det er tilkomst ovenfra til tunnelportal. (opprinnelig fradato: 20040421)</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">3099</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tilkomst ovenfra</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">4608</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">4609</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TilkomstOvenfraTunnelportalOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Tunnelportal"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:TunnelportalType">
      <annotation>
         <documentation>69: Byggverk som benyttes i endene av fjelltunnelene for å beskytte tunnelåpning mot rennende vann og fallende snø, is stein og jord. (HB V440).</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">69</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Tunnelportal</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="TunnelportalType">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="bærerTrafikklast">
                  <annotation>
                     <documentation>12978: Angir om tunnelportal skal kunne bære trafikklast. Dette er tilfelle når det går en kryssende veg over tunnelportalen på tvers av hovedvegen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12978</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Bærer trafikklast</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="typeTverrsnitt">
                  <annotation>
                     <documentation>1131: Angir hvilken type tverrsnitt tunnelportalen har.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">1131</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Type tverrsnitt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="lengde" type="double">
                  <annotation>
                     <documentation>3097: Angir lengde fra der tunnelløpet starter til man møter fjell.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">3097</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Lengde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>11205: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">11205</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="brutus_Id" type="string">
                  <annotation>
                     <documentation>9304: Gir referanse til brudatabanken.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">9304</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Brutus_Id</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="prosjektreferanse" type="string">
                  <annotation>
                     <documentation>11061: Referanse til prosjekt. Det benyttes samme prosjektreferanse som på tilhørende Veganlegg (VT30). Benyttes for lettere å kunne skille nye data fra eksisterende data i NVDB.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">11061</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Prosjektreferanse</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="prosjektInternObjekt_ID" type="string">
                  <annotation>
                     <documentation>12300: Objektmerking. Unik innenfor tilhørende vegprosjekt.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12300</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">ProsjektInternObjekt_ID</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="FKB_ID" type="string">
                  <annotation>
                     <documentation>10849: Refererer til FKB-identitet. Benyttes i forbindelse med felles forvaltning av geometri.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10849</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">FKB_ID</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>4771: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">4771</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="senterlinje" type="gml:CurvePropertyType">
                  <annotation>
                     <documentation>9505: Gir linje/kurve som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">9505</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, linje</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="byggeår" type="integer">
                  <annotation>
                     <documentation>10387: Angir byggeår for vegobjektet</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10387</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Byggeår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="typeLengdesnitt">
                  <annotation>
                     <documentation>11204: Angir hvilken type utforming enden av portalen har. Oppbygd kant langs ende kommer i tillegg.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">11204</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Type lengdesnitt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="VDB_id" type="integer">
                  <annotation>
                     <documentation>7643: Gir objektets id i VDB</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">7643</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">VDB_id</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="høyde" type="double">
                  <annotation>
                     <documentation>3098: Angir høyde av tunnelportal</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">3098</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Høyde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilkomstOvenfra">
                  <annotation>
                     <documentation>3099: Angir om det er tilkomst ovenfra til tunnelportal. (opprinnelig fradato: 20040421)</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">3099</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilkomst ovenfra</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="interntNummer" type="string">
                  <annotation>
                     <documentation>3568: Felt reservert til internt nummersystem. Benyttes f.eks ifbm tunneler</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">3568</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Internt nummer</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligTunnelportalType">
                  <annotation>
                     <documentation>8059: Angir hvem som er ansvarlig for vedlikehold</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">8059</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded"
                        minOccurs="0"
                        name="lineærPosisjon"
                        type="nvdb:LineærPosisjonPunktPropertyType">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="TunnelportalPropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Tunnelportal"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="TypeLengdesnittTunnelportalType">
      <annotation>
         <documentation>11204: Angir hvilken type utforming enden av portalen har. Oppbygd kant langs ende kommer i tillegg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">11204</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type lengdesnitt</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TypeLengdesnittTunnelportalEnumerationType nvdb:TypeLengdesnittTunnelportalOtherType"/>
   </simpleType>
   <simpleType name="TypeLengdesnittTunnelportalEnumerationType">
      <annotation>
         <documentation>11204: Angir hvilken type utforming enden av portalen har. Oppbygd kant langs ende kommer i tillegg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">11204</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type lengdesnitt</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="B">
            <annotation>
               <documentation>18500: Topp av portal skrår økende oppover i enden, som ende på en trompet..</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">18500</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Bue - trompet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="R">
            <annotation>
               <documentation>18498: Topp portal er tilnærmet vannrett i enden.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">18498</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Rett</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="S">
            <annotation>
               <documentation>18499: Topp av portal skrår jevnt opp i enden, som en trakt.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">18499</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Skrå - trakt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TypeLengdesnittTunnelportalOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="TypeTverrsnittTunnelportalType">
      <annotation>
         <documentation>1131: Angir hvilken type tverrsnitt tunnelportalen har.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1131</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type tverrsnitt</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TypeTverrsnittTunnelportalEnumerationType nvdb:TypeTverrsnittTunnelportalOtherType"/>
   </simpleType>
   <simpleType name="TypeTverrsnittTunnelportalEnumerationType">
      <annotation>
         <documentation>1131: Angir hvilken type tverrsnitt tunnelportalen har.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1131</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type tverrsnitt</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="R">
            <annotation>
               <documentation>3420: Profil i utløp av portal har en rektangulær form. Mer detaljer om utforming kan legges på tilleggsinformasjon.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">3420</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Rektangulært</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="S">
            <annotation>
               <documentation>3423: Profil i utløp av portal har en rund form. Mer detaljer om utforming kan legges på tilleggsinformasjon.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">3423</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Sirkulært/buet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="h">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">3424</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Hvelv</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="TR">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">13396</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Traktformet med rektangulært tverrsnitt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ST">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">13397</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Traktformet med sirkulært tverrsnitt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TypeTverrsnittTunnelportalOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTunnelportalType">
      <annotation>
         <documentation>8059: Angir hvem som er ansvarlig for vedlikehold</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">8059</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligTunnelportalEnumerationType nvdb:VedlikeholdsansvarligTunnelportalOtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTunnelportalEnumerationType">
      <annotation>
         <documentation>8059: Angir hvem som er ansvarlig for vedlikehold</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">8059</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">10531</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">10609</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SvV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">10453</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligTunnelportalOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
