<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.43">
   <annotation>
      <documentation>907: Hovedruter for sykling i byer og tettsteder. Rutene er normalt "vedtatt" i kommunedelplan eller kommunale temaplaner. Rutene er ofte utarbeidet i samarbeid mellom Statens vegvesen og aktuell kommune.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <simpleType name="GraderingSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12496: Angivelse av hvor krevende ruta er, basert på forholdsvis objektive kriterier som underlag, tekniske utfordringer, høydemeter og stigningsgrad/eksponering. For mer informasjon, se kapitel om Gradering i Merkehåndboka (www.merkehandboka.no).</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12496</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Gradering</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:GraderingSykkelrute, hovednett bytettstedEnumerationType nvdb:GraderingSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="GraderingSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12496: Angivelse av hvor krevende ruta er, basert på forholdsvis objektive kriterier som underlag, tekniske utfordringer, høydemeter og stigningsgrad/eksponering. For mer informasjon, se kapitel om Gradering i Merkehåndboka (www.merkehandboka.no).</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12496</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Gradering</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="S">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21494</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ekspert</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="G">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21491</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Enkel</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="I">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21495</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ikke gradert</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="R">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21493</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Krevende</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="B">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21492</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Middels</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="GraderingSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="MerkingSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12499: Forteller om det er merking langs en sti, løype, veg, sykkelveg mv. Med merking menes markering for å vise veg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12499</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Merking</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:MerkingSykkelrute, hovednett bytettstedEnumerationType nvdb:MerkingSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="MerkingSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12499: Forteller om det er merking langs en sti, løype, veg, sykkelveg mv. Med merking menes markering for å vise veg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12499</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Merking</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="NEI">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21503</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ikke merket</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="JA">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21502</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Merket</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SM">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21504</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Sesongmerket</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="MerkingSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="RutebetydningSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12498: Klassifisering av tur- og friluftsruter etter hvor brukerne i hovedsak kommer fra. Klassifisering vurderes av "Vedlikeholdsansvarlig" og defineres ut fra bruken av ruta</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12498</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Rutebetydning</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:RutebetydningSykkelrute, hovednett bytettstedEnumerationType nvdb:RutebetydningSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="RutebetydningSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12498: Klassifisering av tur- og friluftsruter etter hvor brukerne i hovedsak kommer fra. Klassifisering vurderes av "Vedlikeholdsansvarlig" og defineres ut fra bruken av ruta</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12498</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Rutebetydning</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="3">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21501</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Lokal betydning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="1">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21499</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nasjonal betydning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="2">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21500</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Regional betydning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="RutebetydningSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="RutebreddeSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12503: Minste sti-, sykkelsti- eller skiløypebredde i grunnriss på rutestrekningen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12503</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Rutebredde</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:RutebreddeSykkelrute, hovednett bytettstedEnumerationType nvdb:RutebreddeSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="RutebreddeSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12503: Minste sti-, sykkelsti- eller skiløypebredde i grunnriss på rutestrekningen.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12503</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Rutebredde</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="0">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21509</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">0 til 0,5 meter</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="1">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21510</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">0,5 opptil 1,5 meter</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="2">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21511</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">1,5 opptil 3 meter</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="3">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21512</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">3 til 6 meter</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="4">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21513</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">over 6 meter</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="RutebreddeSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="RutetypeSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12497: Angivelse av type rute i et differensiert nett.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12497</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Rutetype</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:RutetypeSykkelrute, hovednett bytettstedEnumerationType nvdb:RutetypeSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="RutetypeSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12497: Angivelse av type rute i et differensiert nett.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12497</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Rutetype</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="2">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21497</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Forgreiningsrute</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="1">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21496</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Hovedrute</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="3">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21498</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Materute</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="RutetypeSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="SesongSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12506: Tilrettelagt for sommer, vinter eller hele året.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12506</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Sesong</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:SesongSykkelrute, hovednett bytettstedEnumerationType nvdb:SesongSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="SesongSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12506: Tilrettelagt for sommer, vinter eller hele året.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12506</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Sesong</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="H">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21521</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Helårs</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="S">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21519</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Sommer</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="V">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21520</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Vinter</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="SesongSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="SkiltetSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>10944: Angir om sykkelrute er skiltet eller ikke.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10944</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Skiltet</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:SkiltetSykkelrute, hovednett bytettstedEnumerationType nvdb:SkiltetSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="SkiltetSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>10944: Angir om sykkelrute er skiltet eller ikke.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10944</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Skiltet</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">18288</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">18289</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="SkiltetSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="SpesialSykkelrutetypeSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12495: Rute som er definert ut fra spesiell tilrettelegging, spesielle bruksformål eller historisk opprinnelse.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12495</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Spesial sykkelrutetype</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:SpesialSykkelrutetypeSykkelrute, hovednett bytettstedEnumerationType nvdb:SpesialSykkelrutetypeSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="SpesialSykkelrutetypeSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12495: Rute som er definert ut fra spesiell tilrettelegging, spesielle bruksformål eller historisk opprinnelse.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12495</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Spesial sykkelrutetype</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="9">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21490</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="2">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21487</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Terrengsykling</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="4">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21489</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Transportsykling</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="1">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21486</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Tursykling</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="3">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21488</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Utforsykling</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="SpesialSykkelrutetypeSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <element name="Sykkelrute, hovednett bytettsted"
            substitutionGroup="gml:AbstractFeature"
            type="nvdb:Sykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>907: Hovedruter for sykling i byer og tettsteder. Rutene er normalt "vedtatt" i kommunedelplan eller kommunale temaplaner. Rutene er ofte utarbeidet i samarbeid mellom Statens vegvesen og aktuell kommune.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">907</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Sykkelrute, hovednett bytettsted</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Sykkelrute, hovednett bytettstedType">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element minOccurs="0" name="rutenavn" type="string">
                  <annotation>
                     <documentation>10942: Navn på ruta.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10942</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Rutenavn</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="rutenummer" type="string">
                  <annotation>
                     <documentation>10943: Identifikasjonsnummer eller betegnelse på ruta.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10943</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Rutenummer</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="skiltet"
                        type="nvdb:SkiltetSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>10944: Angir om sykkelrute er skiltet eller ikke.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10944</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Skiltet</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>11652: Supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">11652</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="spesialSykkelrutetype">
                  <annotation>
                     <documentation>12495: Rute som er definert ut fra spesiell tilrettelegging, spesielle bruksformål eller historisk opprinnelse.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12495</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Spesial sykkelrutetype</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="gradering"
                        type="nvdb:GraderingSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12496: Angivelse av hvor krevende ruta er, basert på forholdsvis objektive kriterier som underlag, tekniske utfordringer, høydemeter og stigningsgrad/eksponering. For mer informasjon, se kapitel om Gradering i Merkehåndboka (www.merkehandboka.no).</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12496</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Gradering</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="rutetype"
                        type="nvdb:RutetypeSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12497: Angivelse av type rute i et differensiert nett.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12497</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Rutetype</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="rutebetydning"
                        type="nvdb:RutebetydningSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12498: Klassifisering av tur- og friluftsruter etter hvor brukerne i hovedsak kommer fra. Klassifisering vurderes av "Vedlikeholdsansvarlig" og defineres ut fra bruken av ruta</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12498</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Rutebetydning</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="merking" type="nvdb:MerkingSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12499: Forteller om det er merking langs en sti, løype, veg, sykkelveg mv. Med merking menes markering for å vise veg.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12499</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Merking</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="anleggsnummer" type="string">
                  <annotation>
                     <documentation>12500: Anleggsnummer i idrettsanleggsregisteret gitt i forbindelse med tilskudd gjennom spillemiddelordningen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12500</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Anleggsnummer</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="UUKoblingsID" type="string">
                  <annotation>
                     <documentation>12501: Identifikator for kobling mot data fra kartlegging av Universel Utforming.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12501</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">UU koblingsID</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="underlagstype"
                        type="nvdb:UnderlagstypeSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12502: Type underlag som ruta eller løypa følger - om rutestrekningen har asfalt/betongdekke, går på grus eller på naturlig grunn.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12502</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Underlagstype</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="rutebredde"
                        type="nvdb:RutebreddeSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12503: Minste sti-, sykkelsti- eller skiløypebredde i grunnriss på rutestrekningen.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12503</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Rutebredde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="trafikkbelastning"
                        type="nvdb:TrafikkbelastningSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12504: Grov kategorisering av trafikkbelastning på en strekning.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12504</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Trafikkbelastning</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="belysning" type="boolean">
                  <annotation>
                     <documentation>12505: Om det er belysning eller ikke langs ruten. For eksempel lysløype registreres med egenskapen Belysning og verdien JA.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12505</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Belysning</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="sesong"
                        type="nvdb:SesongSykkelrute, hovednett bytettstedType">
                  <annotation>
                     <documentation>12506: Tilrettelagt for sommer, vinter eller hele året.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12506</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Sesong</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="vedlikeholdsansvarlig" type="string">
                  <annotation>
                     <documentation>12494: Organisasjon/lag/forening, kommune, friluftsråd, reiselivsaktør eller andre som har ansvar for vedlikehold og/eller fremkommelighet av rute.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12494</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Sykkelrute, hovednett bytettstedPropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Sykkelrute, hovednett bytettsted"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="TrafikkbelastningSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12504: Grov kategorisering av trafikkbelastning på en strekning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12504</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Trafikkbelastning</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TrafikkbelastningSykkelrute, hovednett bytettstedEnumerationType nvdb:TrafikkbelastningSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="TrafikkbelastningSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12504: Grov kategorisering av trafikkbelastning på en strekning.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12504</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Trafikkbelastning</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="5">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21518</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Høy trafikkbelastning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="2">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21515</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Lav trafikkbelastning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="3">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21516</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Noe trafikkbelastning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="4">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21517</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Noe trafikkbelastning, sykkelfelt på vegen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="1">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21514</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uten motoriert ferdsel</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TrafikkbelastningSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="UnderlagstypeSykkelrute, hovednett bytettstedType">
      <annotation>
         <documentation>12502: Type underlag som ruta eller løypa følger - om rutestrekningen har asfalt/betongdekke, går på grus eller på naturlig grunn.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12502</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Underlagstype</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:UnderlagstypeSykkelrute, hovednett bytettstedEnumerationType nvdb:UnderlagstypeSykkelrute, hovednett bytettstedOtherType"/>
   </simpleType>
   <simpleType name="UnderlagstypeSykkelrute, hovednett bytettstedEnumerationType">
      <annotation>
         <documentation>12502: Type underlag som ruta eller løypa følger - om rutestrekningen har asfalt/betongdekke, går på grus eller på naturlig grunn.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12502</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Underlagstype</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="4">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21508</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annet underlag</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="1">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21505</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Asfalt/betong</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="2">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21506</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Grus</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="3">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21507</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Naturlig grunn</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="UnderlagstypeSykkelrute, hovednett bytettstedOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
