<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.44">
   <annotation>
      <documentation>472: System for innhenting og videreformidling av radiosignal f.eks. i tunnel.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="DAB-Anlegg"
            substitutionGroup="nvdb:AbstraktRadioanlegg"
            type="nvdb:DAB-AnleggType">
      <annotation>
         <documentation>472: System for innhenting og videreformidling av radiosignal f.eks. i tunnel.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">472</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">DAB-Anlegg</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="DAB-AnleggType">
      <complexContent>
         <extension base="nvdb:AbstraktRadioanleggType">
            <sequence>
               <element name="DABRiks">
                  <annotation>
                     <documentation>10792: Angir om det er DAB Riks.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10792</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">DAB Riks</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="DABRegional">
                  <annotation>
                     <documentation>10793: Angir om det er DAB Regional.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10793</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">DAB Regional</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="DABLokal">
                  <annotation>
                     <documentation>10794: Angir om det er DAB lokal.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10794</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">DAB Lokal</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="innsnakkLokalt">
                  <annotation>
                     <documentation>12651: Angir om det er mulighet for lokalt innsnakk I tilknytning til radioanlegg.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12651</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Innsnakk lokalt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="innsnakkFraVTS">
                  <annotation>
                     <documentation>12652: Angir om det er lokalt mulighet for innsnakk fra VTS til radioanlegg.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">12652</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Innsnakk fra VTS</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="etableringsår" type="integer">
                  <annotation>
                     <documentation>10791: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10791</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>4989: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">4989</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded" minOccurs="0" name="lineærPosisjon">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="DAB-AnleggPropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:DAB-Anlegg"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="DABLokalDAB-AnleggType">
      <annotation>
         <documentation>10794: Angir om det er DAB lokal.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10794</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">DAB Lokal</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:DABLokalDAB-AnleggEnumerationType nvdb:DABLokalDAB-AnleggOtherType"/>
   </simpleType>
   <simpleType name="DABLokalDAB-AnleggEnumerationType">
      <annotation>
         <documentation>10794: Angir om det er DAB lokal.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10794</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">DAB Lokal</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">17543</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">17544</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="DABLokalDAB-AnleggOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="DABRegionalDAB-AnleggType">
      <annotation>
         <documentation>10793: Angir om det er DAB Regional.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10793</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">DAB Regional</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:DABRegionalDAB-AnleggEnumerationType nvdb:DABRegionalDAB-AnleggOtherType"/>
   </simpleType>
   <simpleType name="DABRegionalDAB-AnleggEnumerationType">
      <annotation>
         <documentation>10793: Angir om det er DAB Regional.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10793</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">DAB Regional</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">17545</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">17546</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="DABRegionalDAB-AnleggOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="DABRiksDAB-AnleggType">
      <annotation>
         <documentation>10792: Angir om det er DAB Riks.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10792</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">DAB Riks</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:DABRiksDAB-AnleggEnumerationType nvdb:DABRiksDAB-AnleggOtherType"/>
   </simpleType>
   <simpleType name="DABRiksDAB-AnleggEnumerationType">
      <annotation>
         <documentation>10792: Angir om det er DAB Riks.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">10792</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">DAB Riks</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">17547</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">17548</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="DABRiksDAB-AnleggOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="InnsnakkFraVTSDAB-AnleggType">
      <annotation>
         <documentation>12652: Angir om det er lokalt mulighet for innsnakk fra VTS til radioanlegg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12652</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Innsnakk fra VTS</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:InnsnakkFraVTSDAB-AnleggEnumerationType nvdb:InnsnakkFraVTSDAB-AnleggOtherType"/>
   </simpleType>
   <simpleType name="InnsnakkFraVTSDAB-AnleggEnumerationType">
      <annotation>
         <documentation>12652: Angir om det er lokalt mulighet for innsnakk fra VTS til radioanlegg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12652</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Innsnakk fra VTS</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21862</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21863</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="InnsnakkFraVTSDAB-AnleggOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="InnsnakkLokaltDAB-AnleggType">
      <annotation>
         <documentation>12651: Angir om det er mulighet for lokalt innsnakk I tilknytning til radioanlegg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12651</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Innsnakk lokalt</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:InnsnakkLokaltDAB-AnleggEnumerationType nvdb:InnsnakkLokaltDAB-AnleggOtherType"/>
   </simpleType>
   <simpleType name="InnsnakkLokaltDAB-AnleggEnumerationType">
      <annotation>
         <documentation>12651: Angir om det er mulighet for lokalt innsnakk I tilknytning til radioanlegg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">12651</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Innsnakk lokalt</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="J">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21860</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="N">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">21861</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="InnsnakkLokaltDAB-AnleggOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
