<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML/PS/OLFV_SVV/2.28"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.44">
   <annotation>
      <documentation>1003: Enkeltstående batteri eller en installasjon der to eller flere batterier er koplet sammen til en batteribank. Batteriene i en batteribank kan være oppdelt i pakker av seriekoplede enkeltbatteri.</documentation>
   </annotation>
   <include schemaLocation="OLFV_NV.xsd"/>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <import namespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML/PS/OLFV_SVV/2.28"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="BatteriBatteribank"
            substitutionGroup="nvdb:AbstraktBatteri_Batteribank"
            type="nvdb:BatteriBatteribankType">
      <annotation>
         <documentation>1003: Enkeltstående batteri eller en installasjon der to eller flere batterier er koplet sammen til en batteribank. Batteriene i en batteribank kan være oppdelt i pakker av seriekoplede enkeltbatteri.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1003</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">BatteriBatteribank</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="BatteriBatteribankType">
      <complexContent>
         <extension base="nvdb:AbstraktBatteri_BatteribankType">
            <sequence>
               <element name="bruksområde" type="nvdb:BruksområdeBatteriBatteribankType">
                  <annotation>
                     <documentation>13075: Angir hva anlegget primært benyttes til.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13075</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Bruksområde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="dimensjonerendeLast" type="integer">
                  <annotation>
                     <documentation>13077: Beregnet verdi i watt fra Febdok</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13077</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Dimensjonerende last</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="plassering" type="nvdb:PlasseringBatteriBatteribankType">
                  <annotation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13079</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Plassering</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="antallBatterier" type="integer">
                  <annotation>
                     <documentation>13080: Totalt antall enkeltbatterier. For batteribanker angis totalt antall enkeltbatterier for alle batteripakker i batteribanken.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13080</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Antall batterier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="antallBatteripakker" type="integer">
                  <annotation>
                     <documentation>13330: Angir hvor mange batteripakker det er i batteribanken. I en batteripakke er alle batteriene koplet i samme serie. Batteripakke benevnes også «streng».</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13330</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Antall batteripakker</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="nominellSpenning" type="integer">
                  <annotation>
                     <documentation>13081: Angir nominell spenning per batteri for anlegget. Info hentet fra datablad.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13081</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Nominell spenning</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="metodeForLading">
                  <annotation>
                     <documentation>13082: Angir hvordan Batteri/batteribank lades.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13082</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Metode for lading</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="permanenteBatterier">
                  <annotation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13083</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Permanente batterier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="batterikapasitet" type="integer">
                  <annotation>
                     <documentation>13084: Angi batteriets ytelse ved 20 grader Celsius, 1C.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13084</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Batterikapasitet</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="etableringsår" type="integer">
                  <annotation>
                     <documentation>13085: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13085</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="driftsmerking" type="string">
                  <annotation>
                     <documentation>13078: Angir merking av utstyret. Identitet/navn på forekomst, normalt synlig på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13078</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Driftsmerking</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="produsent" type="string">
                  <annotation>
                     <documentation>13087: Angir navn på produsent/fabrikant av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13087</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Produsent</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="produktnavn" type="string">
                  <annotation>
                     <documentation>13088: Angir produktnavn for vegobjektet. Produktnavn kan inneholde modellnavn, typebetegnelse, typenummer og ev. serienummer.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13088</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Produktnavn</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="eier" type="nvdb:EierBatteriBatteribankType">
                  <annotation>
                     <documentation>13089: Angir hvem som er eier av vegobjektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13089</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0"
                        name="vedlikeholdsansvarlig"
                        type="nvdb:VedlikeholdsansvarligBatteriBatteribankType">
                  <annotation>
                     <documentation>13091: Angir hvem som er ansvarlig for vedlikehold.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13091</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>13145: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13145</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded"
                        minOccurs="0"
                        name="lineærPosisjon"
                        type="nvdb:LineærPosisjonPunktPropertyType">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="BatteriBatteribankPropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:BatteriBatteribank"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="BruksområdeBatteriBatteribankType">
      <annotation>
         <documentation>13075: Angir hva anlegget primært benyttes til.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13075</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Bruksområde</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:BruksområdeBatteriBatteribankEnumerationType nvdb:BruksområdeBatteriBatteribankOtherType"/>
   </simpleType>
   <simpleType name="BruksområdeBatteriBatteribankEnumerationType">
      <annotation>
         <documentation>13075: Angir hva anlegget primært benyttes til.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13075</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Bruksområde</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="a">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22721</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="b">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22715</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Belysning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="f">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22718</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ferist</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="rt">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22719</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Rasteplass/toalettanlegg</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="sp">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22717</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Signalpunkt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="s">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22716</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Skilt</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="trs">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22720</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Trafikkregistreringsstasjon</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="BruksområdeBatteriBatteribankOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="EierBatteriBatteribankType">
      <annotation>
         <documentation>13089: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13089</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:EierBatteriBatteribankEnumerationType nvdb:EierBatteriBatteribankOtherType"/>
   </simpleType>
   <simpleType name="EierBatteriBatteribankEnumerationType">
      <annotation>
         <documentation>13089: Angir hvem som er eier av vegobjektet.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13089</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Eier</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22737</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22735</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22736</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22739</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22734</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Stat, Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <documentation>22738: Verdi benyttes inntil det er avklart hvem som er eier (ingen verdi tolkes som at vegeier er eier).</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22738</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="EierBatteriBatteribankOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="MetodeForLadingBatteriBatteribankType">
      <annotation>
         <documentation>13082: Angir hvordan Batteri/batteribank lades.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13082</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Metode for lading</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:MetodeForLadingBatteriBatteribankEnumerationType nvdb:MetodeForLadingBatteriBatteribankOtherType"/>
   </simpleType>
   <simpleType name="MetodeForLadingBatteriBatteribankEnumerationType">
      <annotation>
         <documentation>13082: Angir hvordan Batteri/batteribank lades.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13082</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Metode for lading</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="agg">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22729</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Aggregat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="bl">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22727</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Batterilader</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="bc">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22730</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Brenselscelle</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="sb">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22731</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Skiftes ved behov</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="sol">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22728</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Solcelleanlegg</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ups">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22726</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Via UPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="MetodeForLadingBatteriBatteribankOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="PermanenteBatterierBatteriBatteribankType">
      <annotation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13083</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Permanente batterier</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:PermanenteBatterierBatteriBatteribankEnumerationType nvdb:PermanenteBatterierBatteriBatteribankOtherType"/>
   </simpleType>
   <simpleType name="PermanenteBatterierBatteriBatteribankEnumerationType">
      <annotation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13083</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Permanente batterier</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="j">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22732</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ja</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="n">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22733</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nei</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="PermanenteBatterierBatteriBatteribankOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="PlasseringBatteriBatteribankType">
      <annotation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13079</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Plassering</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:PlasseringBatteriBatteribankEnumerationType nvdb:PlasseringBatteriBatteribankOtherType"/>
   </simpleType>
   <simpleType name="PlasseringBatteriBatteribankEnumerationType">
      <annotation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13079</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Plassering</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="br">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22722</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Batterirom</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="f">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22725</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fordeling</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ups">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22724</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Internt i UPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="st">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22723</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Skap, teknisk</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="PlasseringBatteriBatteribankOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligBatteriBatteribankType">
      <annotation>
         <documentation>13091: Angir hvem som er ansvarlig for vedlikehold.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13091</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:VedlikeholdsansvarligBatteriBatteribankEnumerationType nvdb:VedlikeholdsansvarligBatteriBatteribankOtherType"/>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligBatteriBatteribankEnumerationType">
      <annotation>
         <documentation>13091: Angir hvem som er ansvarlig for vedlikehold.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13091</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Vedlikeholdsansvarlig</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="FK">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22746</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Fylkeskommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="K">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22741</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kommune</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="NV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22744</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Nye Veier</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="OPS">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22745</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">OPS</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="P">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22742</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Privat</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="SVV">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22740</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Statens vegvesen</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="U">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">22743</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Uavklart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="VedlikeholdsansvarligBatteriBatteribankOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
