<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.45">
   <annotation>
      <documentation>19: Kunst/utsmykking i forbindelse med et veganlegg. Kan være skulpturer, relieff m.m.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="KunstUtsmykking"
            substitutionGroup="nvdb:AbstraktKunstUtsmykking"
            type="nvdb:KunstUtsmykkingType">
      <annotation>
         <documentation>19: Kunst/utsmykking i forbindelse med et veganlegg. Kan være skulpturer, relieff m.m.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">19</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">KunstUtsmykking</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="KunstUtsmykkingType">
      <complexContent>
         <extension base="nvdb:AbstraktKunstUtsmykkingType">
            <sequence>
               <element name="type" type="nvdb:TypeKunstUtsmykkingType">
                  <annotation>
                     <documentation>13414: Angir om dette er kunst  eller utsmykking.

Kunst er inkjøpte selvstendige kunstverk. Noe som er laget av en kunstner. Omfattes av Åndverksloven.

Utsmykking  er en arkitekonisk løsning, noe som forskjønner et sted eller tilfører noe positivt estetisk.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13414</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tittel" type="string">
                  <annotation>
                     <documentation>1733: Angir tittel på kunst/utsmykking.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">1733</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tittel</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="navnPåKunstner" type="string">
                  <annotation>
                     <documentation>1734: Angir navn på kunstner.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">1734</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Navn på kunstner</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="kunstart" type="nvdb:KunstartKunstUtsmykkingType">
                  <annotation>
                     <documentation>1101: Angir hvilken type kunstart kunsten eller utsmykkingen er.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">1101</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Kunstart</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="plassering" type="nvdb:PlasseringKunstUtsmykkingType">
                  <annotation>
                     <documentation>13416: Angir hvor langs vegen og i hvilke omgivelser objektet er plassert.

Kunst er inkjøpte selvstendige kunstverk. Noe som er laget av en kunstner. Omfattes av Åndverksloven.

Utsmykking  er en arkitekonisk løsning, noe som forskjønner et sted eller tilfører noe positivt estetisk.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13416</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Plassering</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="materiale" type="nvdb:MaterialeKunstUtsmykkingType">
                  <annotation>
                     <documentation>13419: Oppgi alle materialer som er brukt, samt andre rekvisitter og gjenstander som er tilknyttet kunstverket. Dette er viktig informasjon for drift og vedlikehold, som forhindrer feilbehandling, og vil sikre kunstverkets levetid.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13419</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Materiale</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="etableringsår" type="integer">
                  <annotation>
                     <documentation>10320: Angir hvilket år vegobjektet ble etablert på stedet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10320</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Etableringsår</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="tilleggsinformasjon" type="string">
                  <annotation>
                     <documentation>10833: Skriv her hvilke materialer kunsten eller utsmykkingen bestar av om den er en kombinasjon av flere materialer.

Skriv her hvilken behandling materialt har fått (for eksempel galvanisert, plulverlakkert, børstet, skurt, pollert, malt)

Skriv her hvilke(t) tiltak som eventuelt er nødvendig reparasjon, utskifting, eller oppretting. 

Samt supplerende informasjon om vegobjektet som ikke framkommer direkte av andre egenskapstyper, men som kan være av relevans for historien til kunstverket eller for drift og vedlikehold. Dette kan for eksempel være infor om avduking, tilgjengeligheten til kunstverket,  omfanget av arealet av et kunstverk som består av mange deler og hva det innebærer.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10833</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Tilleggsinformasjon</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="posisjon" type="gml:PointPropertyType">
                  <annotation>
                     <documentation>4727: Gir punkt som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">4727</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, punkt</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded" minOccurs="0" name="lineærPosisjon">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="KunstUtsmykkingPropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:KunstUtsmykking"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="KunstartKunstUtsmykkingType">
      <annotation>
         <documentation>1101: Angir hvilken type kunstart kunsten eller utsmykkingen er.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1101</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Kunstart</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:KunstartKunstUtsmykkingEnumerationType nvdb:KunstartKunstUtsmykkingOtherType"/>
   </simpleType>
   <simpleType name="KunstartKunstUtsmykkingEnumerationType">
      <annotation>
         <documentation>1101: Angir hvilken type kunstart kunsten eller utsmykkingen er.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">1101</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Kunstart</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="a">
            <annotation>
               <documentation>17856: Kunsten eller utsmykkingen  passer ikke inn i noen av de øvrige kunstartene. Gi beskrivelse i feltet "Tilleggsinformasjon".</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">17856</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annen type</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="bb">
            <annotation>
               <documentation>2491: Horisnotale bilder på dekker. Dette kan for eksempel være belegninger med spesielle billedmønster</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">2491</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Billedbelegning</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="b">
            <annotation>
               <documentation>16795: Spesielle byggverk, f.eks. servicebygg eller utsiktstårn i tilknytning til rasteplasser.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">16795</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Byggverk</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="st">
            <annotation>
               <documentation>2489: En skulptur er et fysisk, tredimensjonalt objekt. Det har en klar avgrenset form, står alene og kan flyttes uten å miste mening. Det består ofte av ett materiale eller en sammenhengende form.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">2489</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Skulptur</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="vb">
            <annotation>
               <documentation>2490: Vertikale bilder montert på eller integrert i en vegg eller flate.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">2490</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Veggbilde</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="gk">
            <annotation>
               <documentation>23481: Gatekunst er kunstneriske uttrykk og en kommentar som skapes og vises i det offentlige rom, som regel på vegger, bygninger, gater eller andre byflater, og som ofte er tilgjengelig for alle utenfor tradisjonelle kunstinstitusjoner. Eksempler er grafitti og sjablongkunst (ikke tagging).</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23481</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Gatekunst</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="la">
            <annotation>
               <documentation>23480: Landart er kunst laget i, av og for landskapet. Kunstverket formes av naturens egne elementer som jord, stein, sand, tre, levende vegetasjon og  vann. Det er ofte utsatt for naturlige prosesser som erosjon, vær og tid , og vil derfor være midlertidige.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23480</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Landart</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ll">
            <annotation>
               <documentation>23479: Dette kan være lyskunst eller lysinstallasjon som alene eller sammen med annen kunst eller arkitektur utgjør en helhet.</documentation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23479</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Lyssetting/Lysinstallasjon</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="KunstartKunstUtsmykkingOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="MaterialeKunstUtsmykkingType">
      <annotation>
         <documentation>13419: Oppgi alle materialer som er brukt, samt andre rekvisitter og gjenstander som er tilknyttet kunstverket. Dette er viktig informasjon for drift og vedlikehold, som forhindrer feilbehandling, og vil sikre kunstverkets levetid.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13419</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Materiale</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:MaterialeKunstUtsmykkingEnumerationType nvdb:MaterialeKunstUtsmykkingOtherType"/>
   </simpleType>
   <simpleType name="MaterialeKunstUtsmykkingEnumerationType">
      <annotation>
         <documentation>13419: Oppgi alle materialer som er brukt, samt andre rekvisitter og gjenstander som er tilknyttet kunstverket. Dette er viktig informasjon for drift og vedlikehold, som forhindrer feilbehandling, og vil sikre kunstverkets levetid.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13419</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Materiale</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="be">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23503</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Betong</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="gl">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23504</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Glass</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ko">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23507</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kombinasjon av flere materialer</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ma">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23506</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Maling</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="me">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23500</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Metall</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="na">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23502</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Naturstein</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="pl">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23505</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Plast</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="tr">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23501</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Tre</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="MaterialeKunstUtsmykkingOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="PlasseringKunstUtsmykkingType">
      <annotation>
         <documentation>13416: Angir hvor langs vegen og i hvilke omgivelser objektet er plassert.

Kunst er inkjøpte selvstendige kunstverk. Noe som er laget av en kunstner. Omfattes av Åndverksloven.

Utsmykking  er en arkitekonisk løsning, noe som forskjønner et sted eller tilfører noe positivt estetisk.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13416</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Plassering</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:PlasseringKunstUtsmykkingEnumerationType nvdb:PlasseringKunstUtsmykkingOtherType"/>
   </simpleType>
   <simpleType name="PlasseringKunstUtsmykkingEnumerationType">
      <annotation>
         <documentation>13416: Angir hvor langs vegen og i hvilke omgivelser objektet er plassert.

Kunst er inkjøpte selvstendige kunstverk. Noe som er laget av en kunstner. Omfattes av Åndverksloven.

Utsmykking  er en arkitekonisk løsning, noe som forskjønner et sted eller tilfører noe positivt estetisk.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13416</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Plassering</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="an">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23492</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="bs">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23491</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Bergskjæring</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="br">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23489</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Bru</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="bk">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23490</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Bygning/Konstruksjon</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="fk">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23487</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Ferjekai</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="fv">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23484</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Frittstående langs veg/gs-veg</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ra">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23486</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Rasteplass</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ru">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23485</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Rundkjøring</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="tu">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23488</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Tunnel</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="PlasseringKunstUtsmykkingOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
   <simpleType name="TypeKunstUtsmykkingType">
      <annotation>
         <documentation>13414: Angir om dette er kunst  eller utsmykking.

Kunst er inkjøpte selvstendige kunstverk. Noe som er laget av en kunstner. Omfattes av Åndverksloven.

Utsmykking  er en arkitekonisk løsning, noe som forskjønner et sted eller tilfører noe positivt estetisk.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13414</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TypeKunstUtsmykkingEnumerationType nvdb:TypeKunstUtsmykkingOtherType"/>
   </simpleType>
   <simpleType name="TypeKunstUtsmykkingEnumerationType">
      <annotation>
         <documentation>13414: Angir om dette er kunst  eller utsmykking.

Kunst er inkjøpte selvstendige kunstverk. Noe som er laget av en kunstner. Omfattes av Åndverksloven.

Utsmykking  er en arkitekonisk løsning, noe som forskjønner et sted eller tilfører noe positivt estetisk.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13414</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="k">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23482</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Kunst</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="u">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23483</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Utsmykking</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TypeKunstUtsmykkingOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
