<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:nvdb="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        elementFormDefault="qualified"
        targetNamespace="https://raw.githubusercontent.com/vegvesen/NVDB-Datakatalogen/master/GML"
        version="2.45">
   <annotation>
      <documentation>503: Område fra ytre skulderkant til tunnelvegg.</documentation>
   </annotation>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="Sideareal tunnel"
            substitutionGroup="nvdb:AbstraktSidearealTunnel"
            type="nvdb:Sideareal tunnelType">
      <annotation>
         <documentation>503: Område fra ytre skulderkant til tunnelvegg.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">503</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Sideareal tunnel</sc:taggedValue>
         </appinfo>
      </annotation>
   </element>
   <complexType name="Sideareal tunnelType">
      <complexContent>
         <extension base="nvdb:AbstraktSidearealTunnelType">
            <sequence>
               <element name="type" type="nvdb:TypeSideareal tunnelType">
                  <annotation>
                     <documentation>13450: Angir hvilken type vegobjektet er av.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13450</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="bredde" type="double">
                  <annotation>
                     <documentation>10784: Angir normal bredde av sidearealet (skulderkant til tunnelvegg). Bredden har betydning for valg av feie-/renholdutstyr for sidearealet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">10784</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Bredde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="maksimalBredde" type="integer">
                  <annotation>
                     <documentation>13449: Gir maksimal bredde av sidearealet (skulderkant til tunnellvegg). Bredden har betydning for valg av feie-/renholdutstyr for sidearealet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13449</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Maksimal bredde</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element minOccurs="0" name="maksimalBreddePåToppFøringskant" type="integer">
                  <annotation>
                     <documentation>13448: Angir maksimal bredde på topp føringskant. Bredden har betydning for valg av feie-/renholdutstyr for sidearealet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">13448</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Maksimal bredde på topp føringskant</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="senterlinje" type="gml:CurvePropertyType">
                  <annotation>
                     <documentation>5008: Gir linje/kurve som geometrisk representerer objektet.</documentation>
                     <appinfo>
                        <sc:taggedValue tag="NVDB_ID">5008</sc:taggedValue>
                        <sc:taggedValue tag="NVDB_navn">Geometri, linje</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element maxOccurs="unbounded" minOccurs="0" name="lineærPosisjon">
                  <annotation>
                     <documentation>Angivelse av posisjon på det linære objektet.</documentation>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="Sideareal tunnelPropertyType">
      <sequence minOccurs="0">
         <element ref="nvdb:Sideareal tunnel"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <simpleType name="TypeSideareal tunnelType">
      <annotation>
         <documentation>13450: Angir hvilken type vegobjektet er av.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13450</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <union memberTypes="nvdb:TypeSideareal tunnelEnumerationType nvdb:TypeSideareal tunnelOtherType"/>
   </simpleType>
   <simpleType name="TypeSideareal tunnelEnumerationType">
      <annotation>
         <documentation>13450: Angir hvilken type vegobjektet er av.</documentation>
         <appinfo>
            <sc:taggedValue tag="NVDB_ID">13450</sc:taggedValue>
            <sc:taggedValue tag="NVDB_navn">Type</sc:taggedValue>
         </appinfo>
      </annotation>
      <restriction base="string">
         <enumeration value="ann">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23569</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Annet</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="ass">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23565</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Asfaltert sideareal</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="føk">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23567</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Føringskant</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="grs">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23564</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Gruset sideareal</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="osf">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23568</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Opphøyd sideareal med føringskant</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
         <enumeration value="opb">
            <annotation>
               <appinfo>
                  <sc:taggedValue tag="NVDB_ID">23566</sc:taggedValue>
                  <sc:taggedValue tag="NVDB_navn">Opphøyd sideareal/bankett</sc:taggedValue>
               </appinfo>
            </annotation>
         </enumeration>
      </restriction>
   </simpleType>
   <simpleType name="TypeSideareal tunnelOtherType">
      <restriction base="string">
         <pattern value="other: \w{2,}"/>
      </restriction>
   </simpleType>
</schema>
